//! Sending and receiving attachments (SPEC §7.1).
//!
//! The attachment ciphertext never rides inside an MLS application message —
//! it is uploaded on its own, to a freshly generated random relay identifier
//! that is not either party's inbox. Only a small reference (where to fetch
//! it, the key to open it, the filename) travels through the normal
//! encrypted message channel. This needs no new relay endpoint: the relay
//! already stores an arbitrary blob under an arbitrary opaque identifier and
//! serves it back to whoever asks for that identifier (`server/src/http.rs`)
//! — a bucket id is just another one, generated by the sender instead of
//! being either party's own address.

use crate::attachments;
use crate::crypto::{CryptoError, AEAD_NAME, CIPHERSUITE_NAME, KEY_AGREEMENT_NAME, SIGNATURE_NAME};
use crate::manifest::Manifest;
use crate::storage::{Direction, QueuedMessage, StoredAttachment, StoredMessage};

use super::compression;
use super::{now, ApiError, Payload, Pouch};

/// A random 128-bit identifier, hex encoded — the same shape the relay's own
/// message ids use, since this travels through the identical `/inbox/{id}`
/// path (SPEC §7.1 step 5: "stores it under a random ID").
fn random_bucket_id() -> String {
    use rand::RngCore;
    let mut bytes = [0u8; 16];
    rand::rngs::OsRng.fill_bytes(&mut bytes);
    hex::encode(bytes)
}

/// A local identifier for a reference message not yet accepted by the relay.
/// Same reasoning as `messaging::local_id` (D-010: no counters).
fn local_id() -> String {
    use rand::RngCore;
    let mut bytes = [0u8; 16];
    rand::rngs::OsRng.fill_bytes(&mut bytes);
    hex::encode(bytes)
}

impl Pouch {
    /// Strips, pads, encrypts, and sends an image attachment.
    ///
    /// `bytes` must be a JPEG, PNG, or WebP file — anything else is refused
    /// rather than sent with its metadata intact (D-038). Returns the
    /// manifest describing what actually happened, the same contract
    /// [`Pouch::send_message`] has.
    pub async fn send_attachment(
        &mut self,
        conversation_id: &str,
        filename: &str,
        bytes: &[u8],
    ) -> Result<Manifest, ApiError> {
        self.flush_outbox().await?;

        if !self.conversations.contains_key(conversation_id) {
            return Err(ApiError::UnknownConversation);
        }

        let mut manifest = Manifest::new_for_attachment(bytes.len());

        let prepared = attachments::prepare(&self.provider, bytes).map_err(ApiError::Attachment)?;
        manifest.stripped(
            prepared.format.label(),
            prepared.strip_report.exif_removed,
            prepared.strip_report.icc_removed,
            prepared.strip_report.other_metadata_removed,
        );
        manifest.padded(prepared.stripped.len(), prepared.padded_len);

        // The blob upload happens outside MLS entirely — it is not this
        // message's ciphertext, and a failure here has nothing queued to
        // retry: the file simply was not sent, honestly reported as such,
        // exactly like a text message failing to route.
        let bucket_id = random_bucket_id();
        let attachment_blob = attachments::encode_blob(&prepared.nonce, &prepared.ciphertext);
        if let Err(err) = self.relay.send(&bucket_id, &attachment_blob).await {
            manifest.failed_at_routing(&err.to_string());
            return Err(err.into());
        }

        let reference = Payload::Attachment {
            bucket_id,
            key: prepared.key.clone(),
            filename: filename.to_string(),
            format: prepared.format.label().to_string(),
        };
        let encoded = serde_json::to_vec(&reference).map_err(|_| CryptoError::Encryption)?;
        let compressed = compression::compress(&encoded).map_err(|_| CryptoError::Encryption)?;
        // The reference travels as an ordinary message payload, so it gets the
        // same compress → pad → encrypt treatment every other payload does
        // (D-041). Not reported at manifest stage 4: that stage already names
        // the padding applied to the attachment *content*, which is the larger
        // and more meaningful number for an attachment. Skipping this pad
        // would leave the reference as the one unpadded blob on the wire —
        // recognisable by size, which is the exact fingerprint padding exists
        // to remove.
        let padded = crate::padding::pad(&compressed);

        let conversation = self
            .conversations
            .get_mut(conversation_id)
            .ok_or(ApiError::UnknownConversation)?;
        let blob = conversation.encrypt(&self.identity, &padded, &self.provider)?;
        manifest.encrypted(
            CIPHERSUITE_NAME,
            AEAD_NAME,
            KEY_AGREEMENT_NAME,
            SIGNATURE_NAME,
        );

        let peer_inbox = conversation.peer_inbox_id().to_string();
        let message_id = match self.relay.send(&peer_inbox, &blob).await {
            Ok(id) => id,
            Err(err) => {
                manifest.failed_at_routing(&err.to_string());

                // Same reasoning as `send_message`'s failure path: the
                // ratchet already advanced when this was encrypted, so the
                // blob is kept and retried whole rather than re-encrypted.
                // The uploaded attachment blob stays put in its bucket —
                // the reference that names it just has not reached the
                // recipient yet.
                let local_id = local_id();
                self.store.put_message(&StoredMessage {
                    id: local_id.clone(),
                    conversation_id: conversation_id.to_string(),
                    direction: Direction::Sent,
                    body: attachment_placeholder(filename),
                    at: now(),
                })?;
                self.store.enqueue(&QueuedMessage {
                    id: local_id,
                    conversation_id: conversation_id.to_string(),
                    peer_inbox,
                    blob,
                    at: now(),
                    attempts: 1,
                    last_error: Some(err.to_string()),
                })?;
                self.persist_mls_state()?;

                return Err(err.into());
            }
        };

        // Same pattern as `send_message`: one route value shared by stages 6
        // and 7, so the two can never disagree about how this went out.
        let route = self.relay.route();
        manifest.routed(route, self.relay.address());
        manifest.sealed(route);
        manifest.queued(&message_id);
        manifest.delivered();

        self.store.put_message(&StoredMessage {
            id: message_id.clone(),
            conversation_id: conversation_id.to_string(),
            direction: Direction::Sent,
            body: attachment_placeholder(filename),
            at: now(),
        })?;
        self.store.put_attachment(&StoredAttachment {
            id: message_id,
            conversation_id: conversation_id.to_string(),
            filename: filename.to_string(),
            format: prepared.format.label().to_string(),
            content: prepared.stripped,
            at: now(),
        })?;
        self.persist_mls_state()?;

        Ok(manifest)
    }

    /// Fetches a received or sent attachment's stripped content, filename
    /// first.
    ///
    /// `None` means `message_id` exists but did not carry an attachment —
    /// callers already know which messages are attachments from the
    /// placeholder body [`Pouch::messages`] returns.
    pub fn attachment(&self, message_id: &str) -> Result<Option<(String, Vec<u8>)>, ApiError> {
        Ok(self
            .store
            .attachment(message_id)?
            .map(|a| (a.filename, a.content)))
    }

    /// Fetches the raw blob for a bucket id and opens it under `key`.
    ///
    /// Shared by the receive path (`messaging::receive_messages`) and kept
    /// here rather than inlined there, since opening an attachment is this
    /// module's concern, not the message loop's.
    pub(super) async fn fetch_attachment(
        &mut self,
        bucket_id: &str,
        key: &[u8],
    ) -> Result<Option<Vec<u8>>, ApiError> {
        let fetched = self.relay.collect(bucket_id).await?;
        let Some(envelope) = fetched.into_iter().next() else {
            return Ok(None);
        };

        let (nonce, ciphertext) =
            attachments::decode_blob(&envelope.blob).map_err(ApiError::Attachment)?;
        let opened = attachments::open(&self.provider, key, &nonce, &ciphertext)
            .map_err(ApiError::Attachment)?;

        self.relay
            .acknowledge(bucket_id, &[envelope.message_id])
            .await?;

        Ok(Some(opened))
    }
}

/// The placeholder body an attachment message shows in a thread until the
/// desktop and Android screens render the image itself. Text, not an icon —
/// SPEC §6.7.3's rule for message state applies equally here.
pub(super) fn attachment_placeholder(filename: &str) -> String {
    format!("[attachment] {filename}")
}
