//! Encrypted backup export and import (SPEC §7.3, screen 10 — §6.7.10).
//!
//! The file this produces is not a database copy. It is a fresh, self-
//! contained encryption of everything a device needs to pick up where a
//! backup left off — identity, MLS state, contacts, conversations, messages,
//! retention settings — protected by a key derived from a recovery key the
//! user holds and this project never stores anywhere. The server has no
//! backup feature (SPEC §7.3) and never sees this file.
//!
//! The crypto is D-037: a fresh AES-128-GCM key per backup, derived from the
//! recovery key via HKDF, used for exactly one encryption. `docs/DECISIONS.md`
//! has the full reasoning for why that is safe despite D-006's general rule.

use rand::rngs::OsRng;
use rand::RngCore;
use serde::{Deserialize, Serialize};

use crate::crypto::{file_crypto, CryptoError, PouchProvider};
use crate::storage::{Direction, RetentionPolicy, StoredContact, StoredMessage};
use crate::transport::RelayConfig;

use super::{ApiError, Pouch};

/// Identifies a Pouch backup file before any attempt to decrypt it.
///
/// Checked first so a file that is simply the wrong kind fails with "this is
/// not a Pouch backup" rather than a confusing decryption error.
const MAGIC: &[u8; 8] = b"POUCHBK1";

/// The only format this build writes or reads. A future incompatible change
/// bumps this and adds a new match arm — old backups do not silently become
/// unreadable without saying why.
const FORMAT_VERSION: u8 = 1;

/// Domain separation for both the HKDF derivation and the AEAD's associated
/// data. Fixed and public; binds "this bears the backup, not the invite-code
/// or safety-number key derivation" even though those use different key
/// material entirely — cheap insurance against a future copy-paste reusing
/// this function's key for something else.
const CONTEXT: &[u8] = b"pouch-backup-v1";

const SALT_BYTES: usize = 16;

/// Recovery-key length, in bytes. 256 bits — deliberately more than the
/// 128-bit AES key it ultimately derives, so the derivation is never the
/// weakest link.
pub const RECOVERY_KEY_BYTES: usize = 32;

/// Things that can go wrong handling a backup file.
#[derive(Debug, thiserror::Error)]
pub enum BackupError {
    /// Not recognisable as a Pouch backup at all.
    #[error("this file is not a Pouch backup")]
    NotABackup,
    /// Recognisable, but from a format this build does not read.
    #[error("this backup was made by a newer version of Pouch")]
    UnsupportedVersion,
    /// The file is shorter than a valid backup could be.
    #[error("this backup file is truncated or corrupted")]
    Truncated,
    /// Decryption failed — wrong recovery key, or the file was altered.
    #[error("this recovery key does not open this backup")]
    WrongKeyOrCorrupted,
    /// The decrypted contents could not be parsed.
    #[error("this backup's contents are not readable")]
    Malformed,
}

/// A fresh recovery key, for the export screen to display and the user to
/// save. 64 hex characters — the same convention `POUCH_KEY` already uses
/// elsewhere in this project, so there is one encoding to explain, not two.
pub fn new_recovery_key() -> Vec<u8> {
    let mut key = vec![0u8; RECOVERY_KEY_BYTES];
    OsRng.fill_bytes(&mut key);
    key
}

/// One conversation's backup-relevant state.
#[derive(Debug, Serialize, Deserialize)]
struct BackupConversation {
    id: String,
    contact_id: String,
    disappear_after: Option<u64>,
}

/// One message, backup framing.
#[derive(Debug, Serialize, Deserialize)]
struct BackupMessage {
    id: String,
    conversation_id: String,
    outgoing: bool,
    body: String,
    at: u64,
}

/// Everything a backup restores. Deliberately not `pub` — a client never
/// touches this shape directly, only `export_backup`/`import_backup`.
#[derive(Debug, Serialize, Deserialize)]
struct BackupPayload {
    display_name: String,
    inbox_id: String,
    signer_public: Vec<u8>,
    /// The MLS state snapshot. Key material (D-025's identity private key
    /// lives inside it) — this is exactly why the file around it is
    /// encrypted, not an incidental detail.
    mls_state: Vec<u8>,
    contacts: Vec<StoredContact>,
    conversations: Vec<BackupConversation>,
    messages: Vec<BackupMessage>,
    retention_policy: String,
}

impl Pouch {
    /// Encrypts everything this device holds into a portable file.
    ///
    /// `recovery_key` is generated by [`new_recovery_key`], shown to the user,
    /// and confirmed saved *before* this is called — SPEC §6.7.10's screen
    /// requires that order, and this function trusts the caller enforced it.
    pub fn export_backup(&self, recovery_key: &[u8]) -> Result<Vec<u8>, ApiError> {
        let mut contacts = Vec::new();
        let mut conversations = Vec::new();
        let mut messages = Vec::new();

        for contact in self.store.contacts()? {
            for conversation_id in self.store.conversations_for(&contact.id)? {
                conversations.push(BackupConversation {
                    id: conversation_id.clone(),
                    contact_id: contact.id.clone(),
                    disappear_after: self.store.disappear_after(&conversation_id)?,
                });
                for m in self.store.messages(&conversation_id)? {
                    messages.push(BackupMessage {
                        id: m.id,
                        conversation_id: m.conversation_id,
                        outgoing: m.direction == Direction::Sent,
                        body: m.body,
                        at: m.at,
                    });
                }
            }
            contacts.push(contact);
        }

        let payload = BackupPayload {
            display_name: self.identity.display_name().to_string(),
            inbox_id: self.identity.inbox_id().to_string(),
            signer_public: self.identity.public_key().to_vec(),
            // The live in-memory state, not `self.store.mls_state()` — the
            // store's copy is only as fresh as the last `persist_mls_state`
            // call, and a backup has to reflect this instant, not the last
            // save point.
            mls_state: self.provider.snapshot()?,
            contacts,
            conversations,
            retention_policy: self.store.retention_policy()?.as_str().to_string(),
            messages,
        };

        let plaintext = serde_json::to_vec(&payload).map_err(|_| CryptoError::Encryption)?;

        let mut salt = vec![0u8; SALT_BYTES];
        OsRng.fill_bytes(&mut salt);
        let key = file_crypto::derive_key(&self.provider, recovery_key, &salt, CONTEXT)
            .map_err(ApiError::Crypto)?;
        let (nonce, ciphertext) = file_crypto::encrypt(&self.provider, &key, &plaintext, CONTEXT)
            .map_err(ApiError::Crypto)?;

        let mut out = Vec::with_capacity(8 + 1 + SALT_BYTES + nonce.len() + ciphertext.len());
        out.extend_from_slice(MAGIC);
        out.push(FORMAT_VERSION);
        out.extend_from_slice(&salt);
        out.extend_from_slice(&nonce);
        out.extend_from_slice(&ciphertext);
        Ok(out)
    }

    /// Restores a backup onto `db_path`, as a fresh device.
    ///
    /// This does not open or merge into an existing identity — it creates the
    /// encrypted local database at `db_path` from nothing and populates it
    /// from the backup. Restoring onto a path that already holds a different
    /// identity is not a supported flow; call this only against a path with
    /// no identity yet, the same precondition `Pouch::create` has.
    pub async fn import_backup(
        db_path: &str,
        db_key: &mut [u8],
        recovery_key: &[u8],
        backup: &[u8],
        relay: RelayConfig,
    ) -> Result<Self, ApiError> {
        let header = parse_header(backup)?;

        let provider = PouchProvider::new();
        let key = file_crypto::derive_key(&provider, recovery_key, header.salt, CONTEXT)
            .map_err(ApiError::Crypto)?;
        let plaintext =
            file_crypto::decrypt(&provider, &key, header.nonce, header.ciphertext, CONTEXT)
                .map_err(|_| BackupError::WrongKeyOrCorrupted)?;
        let payload: BackupPayload =
            serde_json::from_slice(&plaintext).map_err(|_| BackupError::Malformed)?;

        // The key buffer is used twice: once to create the store below, once
        // more to reopen it through the same path `Pouch::open` already uses
        // to rebuild a working identity and conversation set. Cloned before
        // the first use zeroizes the caller's copy, and the clone is
        // zeroized here once both uses are done.
        let mut key_copy = db_key.to_vec();

        {
            let store = crate::storage::LocalStore::open(db_path, db_key)?;
            store.put_identity(
                &payload.display_name,
                &payload.inbox_id,
                &payload.signer_public,
            )?;
            store.put_mls_state(&payload.mls_state)?;
            for contact in &payload.contacts {
                store.put_contact(contact)?;
            }
            for conversation in &payload.conversations {
                store.put_conversation(&conversation.id, &conversation.contact_id)?;
                store.set_disappear_after(&conversation.id, conversation.disappear_after)?;
            }
            for message in &payload.messages {
                store.put_message(&StoredMessage {
                    id: message.id.clone(),
                    conversation_id: message.conversation_id.clone(),
                    direction: if message.outgoing {
                        Direction::Sent
                    } else {
                        Direction::Received
                    },
                    body: message.body.clone(),
                    at: message.at,
                })?;
            }
            store.set_retention_policy(RetentionPolicy::parse(&payload.retention_policy))?;
        }

        let restored = Pouch::open(db_path, &mut key_copy, relay)?;
        crate::keying::erase(&mut key_copy);
        Ok(restored)
    }
}

/// The three parts of a backup file, once its header has checked out.
struct BackupHeader<'a> {
    salt: &'a [u8],
    nonce: &'a [u8],
    ciphertext: &'a [u8],
}

/// Splits a backup file into its salt, nonce, and ciphertext, checking the
/// magic and version first.
fn parse_header(backup: &[u8]) -> Result<BackupHeader<'_>, BackupError> {
    let header_len = MAGIC.len() + 1 + SALT_BYTES + file_crypto::NONCE_BYTES;
    if backup.len() < header_len {
        return Err(BackupError::Truncated);
    }
    if &backup[..MAGIC.len()] != MAGIC {
        return Err(BackupError::NotABackup);
    }
    if backup[MAGIC.len()] != FORMAT_VERSION {
        return Err(BackupError::UnsupportedVersion);
    }

    let salt_start = MAGIC.len() + 1;
    let nonce_start = salt_start + SALT_BYTES;
    let ciphertext_start = nonce_start + file_crypto::NONCE_BYTES;

    Ok(BackupHeader {
        salt: &backup[salt_start..nonce_start],
        nonce: &backup[nonce_start..ciphertext_start],
        ciphertext: &backup[ciphertext_start..],
    })
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn a_recovery_key_is_the_declared_length_and_actually_random() {
        let a = new_recovery_key();
        let b = new_recovery_key();
        assert_eq!(a.len(), RECOVERY_KEY_BYTES);
        assert_ne!(a, b);
    }

    #[test]
    fn an_empty_file_is_reported_as_too_short_not_as_a_decryption_failure() {
        assert!(matches!(parse_header(&[]), Err(BackupError::Truncated)));
    }

    #[test]
    fn a_file_with_the_right_length_but_wrong_magic_is_not_a_backup() {
        let junk = vec![0u8; MAGIC.len() + 1 + SALT_BYTES + file_crypto::NONCE_BYTES + 16];
        assert!(matches!(parse_header(&junk), Err(BackupError::NotABackup)));
    }

    #[test]
    fn a_future_format_version_is_named_rather_than_misread() {
        let mut file = MAGIC.to_vec();
        file.push(FORMAT_VERSION + 1);
        file.extend(vec![0u8; SALT_BYTES + file_crypto::NONCE_BYTES + 16]);
        assert!(matches!(
            parse_header(&file),
            Err(BackupError::UnsupportedVersion)
        ));
    }

    #[test]
    fn parse_header_splits_a_well_formed_file_correctly() {
        let salt = vec![0xAAu8; SALT_BYTES];
        let nonce = vec![0xBBu8; file_crypto::NONCE_BYTES];
        let ciphertext = vec![0xCCu8; 40];

        let mut file = MAGIC.to_vec();
        file.push(FORMAT_VERSION);
        file.extend(&salt);
        file.extend(&nonce);
        file.extend(&ciphertext);

        let header = parse_header(&file).expect("parses");
        assert_eq!(header.salt, salt.as_slice());
        assert_eq!(header.nonce, nonce.as_slice());
        assert_eq!(header.ciphertext, ciphertext.as_slice());
    }
}
